### ISSUE TITLE
Error compling on mac

### ISSUE THREAD

**Issue by MrDadaGuy** [MichaelSasser/pdfcrack-ng#1]
`/Users/me/Documents/code/pdfcrack-ng/src/benchmark.c:327:23: error: use of
      undeclared identifier '__sighandler_t'
`

cmake runs successfully, but I get the above error on make.

**Comment by MichaelSasser** [comment]
I don't have a Mac anymore, but I hope, I've fixed it anyway. Would you try to build it again from [this branch](https://github.com/MichaelSasser/pdfcrack-ng/tree/feature/generic-sighandler_t) and tell me if it worked?

**Comment by MichaelSasser** [comment]
Ok, I tested it with GH actions. If something went wrong, feel free to reopen the issue.
